env:
  - NOT_CRAN=true
language: r
cache: packages
r:
  - oldrel
  - release
  - devel
os:
  - linux
  - osx
dist: focal
jobs:
  exclude:
  - r: devel
    os: osx
  - r: oldrel
    os: osx
addons:
  apt:
    packages:
    - libcgal-dev
    - libglu1-mesa-dev
    - libgdal1-dev
    - libudunits2-dev
    - libmagick++-dev
after_success:
    - Rscript -e 'covr::codecov()'
